//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_PhoneNumber
    {
        public int PhoneNumberID { get; set; }
        public int EmployeeID { get; set; }
        public int PhoneNumber { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int PhoneNumberTypeID { get; set; }
    
        public virtual Employee_Employee Employee_Employee { get; set; }
        public virtual Employee_PhoneNumberType Employee_PhoneNumberType { get; set; }
    }
}
