//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDW56Projet1GabrielEntities : DbContext
    {
        public BDW56Projet1GabrielEntities()
            : base("name=BDW56Projet1GabrielEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Employee_Employee> Employee_Employee { get; set; }
        public virtual DbSet<Employee_PhoneNumber> Employee_PhoneNumber { get; set; }
        public virtual DbSet<Employee_PhoneNumberType> Employee_PhoneNumberType { get; set; }
        public virtual DbSet<Entreprise_Address> Entreprise_Address { get; set; }
        public virtual DbSet<Entreprise_AddressType> Entreprise_AddressType { get; set; }
        public virtual DbSet<Entreprise_Entreprise> Entreprise_Entreprise { get; set; }
    }
}
